version: '3.7'

services:
  film-directory:
    image: bim-film-directory:latest
    container_name: film-directory
    restart: unless-stopped
    volumes:
      - ../film-directory:/var/www/html
    ports:
      - 127.0.0.1:3003:80
    networks:
      - bim_docker

  mariadb:
    image: mariadb:10.4
    container_name: bim-database
    restart: unless-stopped
    volumes:
      - ../film-directory/sql:/sql
      - ../film-directory/secrets:/secrets
      - ../bim-database/:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=bricksinmotion
      - MYSQL_USER_FILE=/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/secrets/mysql_password
    networks:
      - bim_docker

networks:
  bim_docker:
    driver: bridge
